"""Repository interfaces (Protocols) — satisfied by infrastructure/repositories.py.
Application layer depends only on these, mirroring every prior context's
dependency rule exactly."""

from __future__ import annotations

from datetime import date
from typing import Protocol

from app.boards.domain.audit import BoardsAuditEventCategory, BoardsAuditLogRecord
from app.boards.domain.entities import (
    Board,
    BoardCard,
    BoardColumn,
    Sprint,
    SprintBurndownSnapshot,
    Swimlane,
)
from app.platform_core.shared_kernel.types import EntityId, OrgId


class BoardRepository(Protocol):
    async def get_by_id(self, board_id: EntityId) -> Board | None: ...
    async def list_for_project(self, project_id: EntityId, *, include_archived: bool = False) -> list[Board]: ...
    async def add(self, board: Board) -> None: ...
    async def update(self, board: Board) -> None: ...


class BoardColumnRepository(Protocol):
    async def get_by_id(self, column_id: EntityId) -> BoardColumn | None: ...
    async def get_by_name(self, board_id: EntityId, name: str) -> BoardColumn | None: ...
    async def list_for_board(self, board_id: EntityId) -> list[BoardColumn]: ...
    async def add(self, column: BoardColumn) -> None: ...
    async def update(self, column: BoardColumn) -> None: ...
    async def delete(self, column_id: EntityId) -> None: ...


class SwimlaneRepository(Protocol):
    async def get_by_id(self, swimlane_id: EntityId) -> Swimlane | None: ...
    async def list_for_board(self, board_id: EntityId) -> list[Swimlane]: ...
    async def add(self, swimlane: Swimlane) -> None: ...
    async def update(self, swimlane: Swimlane) -> None: ...
    async def delete(self, swimlane_id: EntityId) -> None: ...


class BoardCardRepository(Protocol):
    async def get_by_id(self, card_id: EntityId) -> BoardCard | None: ...
    async def get_by_task(self, board_id: EntityId, task_id: EntityId) -> BoardCard | None: ...
    async def list_for_board(self, board_id: EntityId) -> list[BoardCard]: ...
    async def list_for_column(self, column_id: EntityId) -> list[BoardCard]: ...
    async def list_for_sprint(self, sprint_id: EntityId) -> list[BoardCard]: ...
    async def list_backlog_for_board(self, board_id: EntityId) -> list[BoardCard]: ...
    async def count_for_column(self, column_id: EntityId) -> int: ...
    async def add(self, card: BoardCard) -> None: ...
    async def update(self, card: BoardCard) -> None: ...
    async def delete(self, card_id: EntityId) -> None: ...


class SprintRepository(Protocol):
    async def get_by_id(self, sprint_id: EntityId) -> Sprint | None: ...
    async def list_for_board(self, board_id: EntityId) -> list[Sprint]: ...
    async def get_active_for_board(self, board_id: EntityId) -> Sprint | None: ...
    async def list_all_active(self) -> list[Sprint]: ...
    async def add(self, sprint: Sprint) -> None: ...
    async def update(self, sprint: Sprint) -> None: ...


class SprintBurndownSnapshotRepository(Protocol):
    async def add(self, snapshot: SprintBurndownSnapshot) -> None: ...
    async def get_for_day(self, sprint_id: EntityId, snapshot_date: date) -> SprintBurndownSnapshot | None: ...
    async def list_for_sprint(self, sprint_id: EntityId) -> list[SprintBurndownSnapshot]: ...


class BoardsAuditLogRepository(Protocol):
    async def add(self, record: BoardsAuditLogRecord) -> None: ...
    async def list_for_org(
        self, org_id: OrgId, *, category: BoardsAuditEventCategory | None = None, limit: int = 50
    ) -> list[BoardsAuditLogRecord]: ...
