"""Repository interfaces (Protocols) — satisfied by infrastructure/repositories.py.
The application layer depends only on these, never on the SQLAlchemy implementations."""

from __future__ import annotations

from typing import Protocol

from app.identity.domain.audit import AuditEventCategory, AuditLogRecord
from app.identity.domain.entities import (
    EmailVerificationToken,
    MfaFactor,
    PasswordHistoryEntry,
    PasswordResetToken,
    Session,
    User,
)
from app.identity.domain.invitation import OrganizationInvitation
from app.identity.domain.organization import Organization
from app.identity.domain.rbac import Permission, Role, UserRoleAssignment
from app.identity.domain.security_entities import TrustedDevice
from app.identity.domain.team import Team, TeamMembership
from app.platform_core.api.sorting import SortField
from app.platform_core.shared_kernel.types import EntityId, OrgId, UserId


class UserRepository(Protocol):
    async def get_by_id(self, user_id: EntityId) -> User | None: ...
    async def get_by_email(self, org_id: OrgId, email: str) -> User | None: ...
    async def list_by_org(self, org_id: OrgId, *, offset: int = 0, limit: int = 50) -> list[User]: ...
    async def search(
        self,
        org_id: OrgId,
        *,
        query: str | None = None,
        status: str | None = None,
        sort: list[SortField] | None = None,
        offset: int = 0,
        limit: int = 50,
    ) -> tuple[list[User], int]:
        """Dashboard-facing member listing: free-text search (email or
        display_name), status filter, sort, and the total match count
        needed for pagination UI. Returns (page_of_users, total_matching_count)."""
        ...
    async def add(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...


class SessionRepository(Protocol):
    async def get_by_id(self, session_id: EntityId) -> Session | None: ...
    async def get_by_refresh_token_hash(self, refresh_token_hash: str) -> Session | None: ...
    async def list_active_for_user(self, user_id: EntityId) -> list[Session]: ...
    async def add(self, session: Session) -> None: ...
    async def update(self, session: Session) -> None: ...


class MfaFactorRepository(Protocol):
    async def get_by_id(self, factor_id: EntityId) -> MfaFactor | None: ...
    async def list_for_user(self, user_id: EntityId) -> list[MfaFactor]: ...
    async def add(self, factor: MfaFactor) -> None: ...
    async def update(self, factor: MfaFactor) -> None: ...
    async def delete(self, factor_id: EntityId) -> None: ...


class EmailVerificationTokenRepository(Protocol):
    async def get_by_token_hash(self, token_hash: str) -> EmailVerificationToken | None: ...
    async def add(self, token: EmailVerificationToken) -> None: ...
    async def update(self, token: EmailVerificationToken) -> None: ...
    async def invalidate_outstanding_for_user(self, user_id: EntityId) -> None: ...


class PasswordResetTokenRepository(Protocol):
    async def get_by_token_hash(self, token_hash: str) -> PasswordResetToken | None: ...
    async def add(self, token: PasswordResetToken) -> None: ...
    async def update(self, token: PasswordResetToken) -> None: ...
    async def invalidate_outstanding_for_user(self, user_id: EntityId) -> None: ...


class PasswordHistoryRepository(Protocol):
    async def recent_for_user(self, user_id: EntityId, *, limit: int = 5) -> list[PasswordHistoryEntry]: ...
    async def add(self, entry: PasswordHistoryEntry) -> None: ...


class OrganizationRepository(Protocol):
    async def get_by_id(self, org_id: EntityId) -> Organization | None: ...
    async def get_by_slug(self, slug: str) -> Organization | None: ...
    async def add(self, organization: Organization) -> None: ...
    async def update(self, organization: Organization) -> None: ...


class OrganizationInvitationRepository(Protocol):
    async def get_by_id(self, invitation_id: EntityId) -> OrganizationInvitation | None: ...
    async def get_by_token_hash(self, token_hash: str) -> OrganizationInvitation | None: ...
    async def get_pending_for_email(self, org_id: OrgId, email: str) -> OrganizationInvitation | None: ...
    async def list_pending_for_org(self, org_id: OrgId, *, offset: int = 0, limit: int = 50) -> list[OrganizationInvitation]: ...
    async def add(self, invitation: OrganizationInvitation) -> None: ...
    async def update(self, invitation: OrganizationInvitation) -> None: ...


class TeamRepository(Protocol):
    async def get_by_id(self, team_id: EntityId) -> Team | None: ...
    async def list_for_org(self, org_id: OrgId) -> list[Team]: ...
    async def add(self, team: Team) -> None: ...
    async def update(self, team: Team) -> None: ...


class TeamMembershipRepository(Protocol):
    async def get(self, team_id: EntityId, user_id: UserId) -> TeamMembership | None: ...
    async def list_for_team(self, team_id: EntityId) -> list[TeamMembership]: ...
    async def list_for_user(self, user_id: UserId) -> list[TeamMembership]: ...
    async def add(self, membership: TeamMembership) -> None: ...
    async def update(self, membership: TeamMembership) -> None: ...
    async def delete(self, membership_id: EntityId) -> None: ...


class RoleRepository(Protocol):
    async def get_by_id(self, role_id: EntityId) -> Role | None: ...
    async def get_by_name(self, org_id: OrgId | None, name: str) -> Role | None: ...
    async def list_system_roles(self) -> list[Role]: ...
    async def list_for_org(self, org_id: OrgId) -> list[Role]: ...
    async def add(self, role: Role) -> None: ...
    async def update(self, role: Role) -> None: ...
    async def delete(self, role_id: EntityId) -> None: ...


class PermissionRepository(Protocol):
    async def get_by_id(self, permission_id: EntityId) -> Permission | None: ...
    async def get_by_key(self, resource: str, action: str) -> Permission | None: ...
    async def list_all(self) -> list[Permission]: ...
    async def add(self, permission: Permission) -> None: ...


class UserRoleAssignmentRepository(Protocol):
    async def list_for_user(self, user_id: UserId, org_id: OrgId) -> list[UserRoleAssignment]: ...
    async def get(self, user_id: UserId, role_id: EntityId) -> UserRoleAssignment | None: ...
    async def add(self, assignment: UserRoleAssignment) -> None: ...
    async def delete(self, assignment_id: EntityId) -> None: ...


class TrustedDeviceRepository(Protocol):
    async def get_by_fingerprint_hash(self, user_id: UserId, fingerprint_hash: str) -> TrustedDevice | None: ...
    async def list_for_user(self, user_id: UserId) -> list[TrustedDevice]: ...
    async def add(self, device: TrustedDevice) -> None: ...
    async def delete(self, device_id: EntityId) -> None: ...


class AuditLogRepository(Protocol):
    async def add(self, record: AuditLogRecord) -> None: ...
    async def list_for_org(
        self, org_id: OrgId, *, category: AuditEventCategory | None = None, limit: int = 50
    ) -> list[AuditLogRecord]: ...
