"""Repository interfaces (Protocols) — satisfied by infrastructure/repositories.py.
Application layer depends only on these, mirroring every prior context's
dependency rule exactly."""

from __future__ import annotations

from typing import Protocol

from app.discord_integration.domain.audit import DiscordAuditEventCategory, DiscordAuditLogRecord
from app.discord_integration.domain.entities import GuildLink, GuildSetupToken
from app.platform_core.shared_kernel.types import EntityId, OrgId


class GuildSetupTokenRepository(Protocol):
    async def get_by_token_hash(self, token_hash: str) -> GuildSetupToken | None: ...
    async def add(self, token: GuildSetupToken) -> None: ...
    async def update(self, token: GuildSetupToken) -> None: ...
    async def invalidate_outstanding_for_org(self, org_id: OrgId) -> None: ...


class GuildLinkRepository(Protocol):
    async def get_by_id(self, guild_link_id: EntityId) -> GuildLink | None: ...
    async def get_by_discord_guild_id(self, discord_guild_id: str) -> GuildLink | None: ...
    async def get_active_by_discord_guild_id(self, discord_guild_id: str) -> GuildLink | None: ...
    async def list_for_org(self, org_id: OrgId) -> list[GuildLink]: ...
    async def add(self, link: GuildLink) -> None: ...
    async def update(self, link: GuildLink) -> None: ...


class DiscordAuditLogRepository(Protocol):
    async def add(self, record: DiscordAuditLogRecord) -> None: ...
    async def list_for_org(
        self, org_id: OrgId, *, category: DiscordAuditEventCategory | None = None, limit: int = 50
    ) -> list[DiscordAuditLogRecord]: ...
