"""Repository interfaces (Protocols) — satisfied by infrastructure/repositories.py.
Application layer depends only on these, mirroring Identity's and Projects'
dependency rule exactly."""

from __future__ import annotations

from typing import Protocol

from app.tasks.domain.audit import TasksAuditEventCategory, TasksAuditLogRecord
from app.tasks.domain.entities import (
    Label,
    Task,
    TaskAssignment,
    TaskAssignmentHistoryRecord,
    TaskDependency,
    TaskLabel,
    TaskRelation,
)
from app.tasks.domain.workflow import TaskPriority, TaskStatus, WorkflowDefinition
from app.platform_core.shared_kernel.types import EntityId, OrgId, UserId


class TaskRepository(Protocol):
    async def get_by_id(self, task_id: EntityId) -> Task | None: ...
    async def list_for_project(
        self, project_id: EntityId, *, include_archived: bool = False
    ) -> list[Task]: ...
    async def list_subtasks(self, parent_task_id: EntityId) -> list[Task]: ...
    async def list_by_ids(self, task_ids: list[EntityId]) -> list[Task]: ...
    async def list_overdue_for_project(self, project_id: EntityId) -> list[Task]: ...
    async def count_overdue_all(self) -> int: ...
    async def search(
        self,
        project_id: EntityId,
        *,
        status: TaskStatus | None = None,
        priority: TaskPriority | None = None,
        label_id: EntityId | None = None,
        assignee_user_id: UserId | None = None,
        search_text: str | None = None,
        include_archived: bool = False,
        parent_task_id: EntityId | None = None,
    ) -> list[Task]: ...
    async def add(self, task: Task) -> None: ...
    async def update(self, task: Task) -> None: ...


class TaskAssignmentRepository(Protocol):
    async def get(self, task_id: EntityId, user_id: UserId) -> TaskAssignment | None: ...
    async def list_for_task(self, task_id: EntityId) -> list[TaskAssignment]: ...
    async def list_for_user(self, user_id: UserId) -> list[TaskAssignment]: ...
    async def add(self, assignment: TaskAssignment) -> None: ...
    async def update(self, assignment: TaskAssignment) -> None: ...
    async def delete(self, assignment_id: EntityId) -> None: ...


class TaskAssignmentHistoryRepository(Protocol):
    async def add(self, record: TaskAssignmentHistoryRecord) -> None: ...
    async def list_for_task(self, task_id: EntityId) -> list[TaskAssignmentHistoryRecord]: ...


class LabelRepository(Protocol):
    async def get_by_id(self, label_id: EntityId) -> Label | None: ...
    async def get_by_name(self, project_id: EntityId, name: str) -> Label | None: ...
    async def list_for_project(self, project_id: EntityId) -> list[Label]: ...
    async def add(self, label: Label) -> None: ...
    async def update(self, label: Label) -> None: ...
    async def delete(self, label_id: EntityId) -> None: ...


class TaskLabelRepository(Protocol):
    async def get(self, task_id: EntityId, label_id: EntityId) -> TaskLabel | None: ...
    async def list_for_task(self, task_id: EntityId) -> list[TaskLabel]: ...
    async def list_task_ids_for_label(self, label_id: EntityId) -> list[EntityId]: ...
    async def add(self, task_label: TaskLabel) -> None: ...
    async def delete(self, task_label_id: EntityId) -> None: ...


class TaskDependencyRepository(Protocol):
    async def get(self, task_id: EntityId, depends_on_task_id: EntityId) -> TaskDependency | None: ...
    async def list_dependencies(self, task_id: EntityId) -> list[TaskDependency]: ...
    async def list_dependents(self, task_id: EntityId) -> list[TaskDependency]: ...
    async def add(self, dependency: TaskDependency) -> None: ...
    async def delete(self, dependency_id: EntityId) -> None: ...


class TaskRelationRepository(Protocol):
    async def get(self, task_id: EntityId, related_task_id: EntityId) -> TaskRelation | None: ...
    async def list_for_task(self, task_id: EntityId) -> list[TaskRelation]: ...
    async def add(self, relation: TaskRelation) -> None: ...
    async def delete(self, relation_id: EntityId) -> None: ...


class WorkflowDefinitionRepository(Protocol):
    async def get_by_id(self, workflow_id: EntityId) -> WorkflowDefinition | None: ...
    async def get_for_project(self, project_id: EntityId) -> WorkflowDefinition | None: ...
    async def add(self, workflow: WorkflowDefinition) -> None: ...
    async def update(self, workflow: WorkflowDefinition) -> None: ...


class TasksAuditLogRepository(Protocol):
    async def add(self, record: TasksAuditLogRecord) -> None: ...
    async def list_for_org(
        self, org_id: OrgId, *, category: TasksAuditEventCategory | None = None, limit: int = 50
    ) -> list[TasksAuditLogRecord]: ...
