"""Repository interfaces (Protocols) — satisfied by infrastructure/repositories.py.
Application layer depends only on these, mirroring Identity's dependency rule."""

from __future__ import annotations

from typing import Protocol

from app.projects.domain.audit import ProjectsAuditEventCategory, ProjectsAuditLogRecord
from app.projects.domain.entities import (
    Project,
    ProjectMembership,
    ProjectTemplate,
    Workspace,
    WorkspaceMembership,
)
from app.platform_core.shared_kernel.types import EntityId, OrgId, UserId


class WorkspaceRepository(Protocol):
    async def get_by_id(self, workspace_id: EntityId) -> Workspace | None: ...
    async def get_by_slug(self, org_id: OrgId, slug: str) -> Workspace | None: ...
    async def list_for_org(self, org_id: OrgId) -> list[Workspace]: ...
    async def add(self, workspace: Workspace) -> None: ...
    async def update(self, workspace: Workspace) -> None: ...


class WorkspaceMembershipRepository(Protocol):
    async def get(self, workspace_id: EntityId, user_id: UserId) -> WorkspaceMembership | None: ...
    async def list_for_workspace(self, workspace_id: EntityId) -> list[WorkspaceMembership]: ...
    async def list_for_user(self, user_id: UserId) -> list[WorkspaceMembership]: ...
    async def add(self, membership: WorkspaceMembership) -> None: ...
    async def update(self, membership: WorkspaceMembership) -> None: ...
    async def delete(self, membership_id: EntityId) -> None: ...


class ProjectRepository(Protocol):
    async def get_by_id(self, project_id: EntityId) -> Project | None: ...
    async def list_for_workspace(self, workspace_id: EntityId, *, include_archived: bool = False) -> list[Project]: ...
    async def add(self, project: Project) -> None: ...
    async def update(self, project: Project) -> None: ...


class ProjectMembershipRepository(Protocol):
    async def get(self, project_id: EntityId, user_id: UserId) -> ProjectMembership | None: ...
    async def list_for_project(self, project_id: EntityId) -> list[ProjectMembership]: ...
    async def list_for_user(self, user_id: UserId) -> list[ProjectMembership]: ...
    async def count_owners(self, project_id: EntityId) -> int: ...
    async def add(self, membership: ProjectMembership) -> None: ...
    async def update(self, membership: ProjectMembership) -> None: ...
    async def delete(self, membership_id: EntityId) -> None: ...


class ProjectTemplateRepository(Protocol):
    async def get_by_id(self, template_id: EntityId) -> ProjectTemplate | None: ...
    async def list_for_org(self, org_id: OrgId) -> list[ProjectTemplate]: ...
    async def get_default(self, org_id: OrgId) -> ProjectTemplate | None: ...
    async def add(self, template: ProjectTemplate) -> None: ...
    async def update(self, template: ProjectTemplate) -> None: ...
    async def delete(self, template_id: EntityId) -> None: ...


class ProjectsAuditLogRepository(Protocol):
    async def add(self, record: ProjectsAuditLogRecord) -> None: ...
    async def list_for_org(
        self, org_id: OrgId, *, category: ProjectsAuditEventCategory | None = None, limit: int = 50
    ) -> list[ProjectsAuditLogRecord]: ...
