"""Repository interfaces (Protocols) — satisfied by infrastructure/repositories.py.
Application layer depends only on these, mirroring every prior context's
dependency rule exactly."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from app.workflow_engine.domain.audit import WorkflowAuditEventCategory, WorkflowAuditLogRecord
from app.workflow_engine.domain.entities import (
    PendingActionStatus,
    PendingAutomationAction,
    TransitionRule,
    WorkflowAction,
    WorkflowApprovalRequest,
    WorkflowChecklistCompletion,
    WorkflowChecklistItem,
    WorkflowCondition,
    WorkflowActivityEntry,
    WorkflowDefinition,
    WorkflowExecutionRecord,
    WorkflowState,
    WorkflowTaskState,
    WorkflowTransition,
)
from app.platform_core.shared_kernel.types import EntityId, OrgId


class WorkflowRepository(Protocol):
    async def get_by_id(self, workflow_id: EntityId) -> WorkflowDefinition | None: ...
    async def list_for_project(self, project_id: EntityId, *, include_archived: bool = False) -> list[WorkflowDefinition]: ...
    async def add(self, workflow: WorkflowDefinition) -> None: ...
    async def update(self, workflow: WorkflowDefinition) -> None: ...


class WorkflowStateRepository(Protocol):
    async def get_by_id(self, state_id: EntityId) -> WorkflowState | None: ...
    async def get_by_name(self, workflow_id: EntityId, name: str) -> WorkflowState | None: ...
    async def get_initial(self, workflow_id: EntityId) -> WorkflowState | None: ...
    async def list_for_workflow(self, workflow_id: EntityId) -> list[WorkflowState]: ...
    async def add(self, state: WorkflowState) -> None: ...
    async def update(self, state: WorkflowState) -> None: ...
    async def delete(self, state_id: EntityId) -> None: ...


class WorkflowTransitionRepository(Protocol):
    async def get_by_id(self, transition_id: EntityId) -> WorkflowTransition | None: ...
    async def list_for_workflow(self, workflow_id: EntityId) -> list[WorkflowTransition]: ...
    async def list_from_state(self, from_state_id: EntityId) -> list[WorkflowTransition]: ...
    async def references_state(self, state_id: EntityId) -> bool: ...
    async def add(self, transition: WorkflowTransition) -> None: ...
    async def update(self, transition: WorkflowTransition) -> None: ...
    async def delete(self, transition_id: EntityId) -> None: ...


class TransitionRuleRepository(Protocol):
    async def get_by_id(self, rule_id: EntityId) -> TransitionRule | None: ...
    async def list_for_transition(self, transition_id: EntityId) -> list[TransitionRule]: ...
    async def add(self, rule: TransitionRule) -> None: ...
    async def delete(self, rule_id: EntityId) -> None: ...


class WorkflowActionRepository(Protocol):
    async def get_by_id(self, action_id: EntityId) -> WorkflowAction | None: ...
    async def list_for_transition(self, transition_id: EntityId) -> list[WorkflowAction]: ...
    async def add(self, action: WorkflowAction) -> None: ...
    async def delete(self, action_id: EntityId) -> None: ...


class WorkflowConditionRepository(Protocol):
    async def get_by_id(self, condition_id: EntityId) -> WorkflowCondition | None: ...
    async def list_for_transition(self, transition_id: EntityId) -> list[WorkflowCondition]: ...
    async def add(self, condition: WorkflowCondition) -> None: ...
    async def delete(self, condition_id: EntityId) -> None: ...


class WorkflowTaskStateRepository(Protocol):
    async def get(self, workflow_id: EntityId, task_id: EntityId) -> WorkflowTaskState | None: ...
    async def list_for_task(self, task_id: EntityId) -> list[WorkflowTaskState]: ...
    async def add(self, task_state: WorkflowTaskState) -> None: ...
    async def update(self, task_state: WorkflowTaskState) -> None: ...


class WorkflowExecutionRecordRepository(Protocol):
    async def add(self, record: WorkflowExecutionRecord) -> None: ...
    async def list_for_task(self, workflow_id: EntityId, task_id: EntityId) -> list[WorkflowExecutionRecord]: ...


class PendingAutomationActionRepository(Protocol):
    async def get_by_id(self, pending_action_id: EntityId) -> PendingAutomationAction | None: ...
    async def list_due(self, *, before: datetime, status: PendingActionStatus = PendingActionStatus.PENDING) -> list[PendingAutomationAction]: ...
    async def add(self, pending_action: PendingAutomationAction) -> None: ...
    async def update(self, pending_action: PendingAutomationAction) -> None: ...


class WorkflowApprovalRequestRepository(Protocol):
    async def get_by_id(self, approval_id: EntityId) -> WorkflowApprovalRequest | None: ...
    async def get_latest_for_task(self, transition_id: EntityId, task_id: EntityId) -> WorkflowApprovalRequest | None: ...
    async def add(self, approval: WorkflowApprovalRequest) -> None: ...
    async def update(self, approval: WorkflowApprovalRequest) -> None: ...


class WorkflowChecklistItemRepository(Protocol):
    async def get_by_id(self, item_id: EntityId) -> WorkflowChecklistItem | None: ...
    async def list_for_transition(self, transition_id: EntityId) -> list[WorkflowChecklistItem]: ...
    async def add(self, item: WorkflowChecklistItem) -> None: ...
    async def update(self, item: WorkflowChecklistItem) -> None: ...
    async def delete(self, item_id: EntityId) -> None: ...


class WorkflowChecklistCompletionRepository(Protocol):
    async def get(self, checklist_item_id: EntityId, task_id: EntityId) -> WorkflowChecklistCompletion | None: ...
    async def list_for_task(self, transition_id: EntityId, task_id: EntityId) -> list[WorkflowChecklistCompletion]: ...
    async def add(self, completion: WorkflowChecklistCompletion) -> None: ...


class WorkflowActivityEntryRepository(Protocol):
    async def add(self, entry: WorkflowActivityEntry) -> None: ...
    async def list_for_task(self, workflow_id: EntityId, task_id: EntityId) -> list[WorkflowActivityEntry]: ...


class WorkflowAuditLogRepository(Protocol):
    async def add(self, record: WorkflowAuditLogRecord) -> None: ...
    async def list_for_org(
        self, org_id: OrgId, *, category: WorkflowAuditEventCategory | None = None, limit: int = 50
    ) -> list[WorkflowAuditLogRecord]: ...
